server:
  port: ${PORT:8085}
spring:
  application:
    name: notification-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${SPRING_DATASOURCE_USERNAME:eventhub}
    password: ${SPRING_DATASOURCE_PASSWORD:eventhub}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:eventhub}
    password: ${SPRING_RABBITMQ_PASSWORD:eventhub}
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
eventhub:
  jwt:
    secret: ${JWT_SECRET:change-me-to-a-long-random-secret}
  rabbitmq:
    exchange: eventhub.exchange
    queues:
      booking-created: notification.booking.created.queue
      booking-cancelled: notification.booking.cancelled.queue
      payment-succeeded: notification.payment.succeeded.queue
      payment-failed: notification.payment.failed.queue
    routing-keys:
      booking-created: booking.created
      booking-cancelled: booking.cancelled
      payment-succeeded: payment.succeeded
      payment-failed: payment.failed
