ALTER TABLE events ADD COLUMN IF NOT EXISTS status VARCHAR(32);

UPDATE events
SET status = CASE
    WHEN end_time IS NOT NULL AND end_time <= CURRENT_TIMESTAMP THEN 'COMPLETED'
    ELSE 'PUBLISHED'
END
WHERE status IS NULL;

ALTER TABLE events ALTER COLUMN status SET DEFAULT 'DRAFT';
ALTER TABLE events ALTER COLUMN status SET NOT NULL;
