server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  codec:
    max-in-memory-size: 10MB

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "https://event-hub-seven-lac.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-Internal-Api-Key

      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/users/**

        - id: event-service
          uri: ${EVENT_SERVICE_URL}
          predicates:
            - Path=/api/events/**,/events/**

        - id: booking-service
          uri: ${BOOKING_SERVICE_URL}
          predicates:
            - Path=/api/bookings/**,/api/tickets/**,/api/resale-tickets/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL}
          predicates:
            - Path=/api/notifications/**

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL}
          predicates:
            - Path=/api/payments/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
