-- Add composite index for ticket_assets to optimize "my tickets" queries
-- Query pattern: WHERE owner_id = ? AND status = 'OWNED' ORDER BY created_at DESC

CREATE INDEX IF NOT EXISTS idx_ticket_assets_owner_status
    ON ticket_assets(owner_id, status, created_at DESC);

-- Comment: Replaces/faster than separate indexes on owner_id and status
</parameter3_name>
</parameter3_name>
<parameter4_name>
</parameter4_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</parameter1_name>
</write_to_file>